[package]
name = "library"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.4"
proconio = {version = "=0.4.1", features = ["derive"]}
